### PR TITLE
Data profile

### PR DESCRIPTION
**Pull request by abelsiqueira**
Very large rework in progress.

Related to #58

### CODE REVIEW

**Comment by abelsiqueira** [comment]
By the way, I think this will entail 2.0, since there are major changes.

**Comment by abelsiqueira** [comment]
Maybe it would be better to merge this in `develop` and then build the data profile on top? @rgaiacs, @lrsantos11, do you want to review?

**Comment by rgaiacs** [comment]
> do you want to review?

I can review on 8th July (during a flight). Or at EuroPython. I can't do early.

**Comment by abelsiqueira** [comment]
That's cool. I'll be working on some extra things for this.
Please don't feel obligated to work on this, I know you're on a different field now, so I understand if you rather not use your time on this.

**Comment by abelsiqueira** [comment]
Closing as this is too stale

**Pull request closed without merging**
